syntax = "proto3";

package authapi;

service AuthAPI {
    rpc Login(LoginRequest) returns (LoginResponse) {}
    rpc Authenticate(AuthRequest) returns (AuthResponse) {}
    rpc SignUP(SignUPRequest) returns (SignUPResponse) {}
    rpc OTPValidation(OTPRequest) returns (OTPResponse) {}
};

message LoginRequest {
    Email email =1;
};

message LoginResponse {
    bool otp_sent =1;
}

message AuthRequest {
    string token = 1;
};
message AuthResponse {

}
message SignUPRequest {
    Email email = 1;
};

message OTPResponse {}
message OTPRequest {}
message SignUPResponse{}

message Email {
    string email = 1;
}