// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: proto/v2/auth_api.proto

package auth_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthAPIService_Login_FullMethodName        = "/proto.v2.AuthAPIService/Login"
	AuthAPIService_Auth_FullMethodName         = "/proto.v2.AuthAPIService/Auth"
	AuthAPIService_Signup_FullMethodName       = "/proto.v2.AuthAPIService/Signup"
	AuthAPIService_OTP_FullMethodName          = "/proto.v2.AuthAPIService/OTP"
	AuthAPIService_SignUPVerify_FullMethodName = "/proto.v2.AuthAPIService/SignUPVerify"
	AuthAPIService_LoginVerify_FullMethodName  = "/proto.v2.AuthAPIService/LoginVerify"
)

// AuthAPIServiceClient is the client API for AuthAPIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthAPIServiceClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	OTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*OTPResponse, error)
	SignUPVerify(ctx context.Context, in *SignUPVerifyRequest, opts ...grpc.CallOption) (*SignUPVerifyResponse, error)
	LoginVerify(ctx context.Context, in *LoginVerifyRequest, opts ...grpc.CallOption) (*LoginVerifyResponse, error)
}

type authAPIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthAPIServiceClient(cc grpc.ClientConnInterface) AuthAPIServiceClient {
	return &authAPIServiceClient{cc}
}

func (c *authAPIServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAPIServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_Auth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAPIServiceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_Signup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAPIServiceClient) OTP(ctx context.Context, in *OTPRequest, opts ...grpc.CallOption) (*OTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OTPResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_OTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAPIServiceClient) SignUPVerify(ctx context.Context, in *SignUPVerifyRequest, opts ...grpc.CallOption) (*SignUPVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignUPVerifyResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_SignUPVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authAPIServiceClient) LoginVerify(ctx context.Context, in *LoginVerifyRequest, opts ...grpc.CallOption) (*LoginVerifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginVerifyResponse)
	err := c.cc.Invoke(ctx, AuthAPIService_LoginVerify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthAPIServiceServer is the server API for AuthAPIService service.
// All implementations must embed UnimplementedAuthAPIServiceServer
// for forward compatibility.
type AuthAPIServiceServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	OTP(context.Context, *OTPRequest) (*OTPResponse, error)
	SignUPVerify(context.Context, *SignUPVerifyRequest) (*SignUPVerifyResponse, error)
	LoginVerify(context.Context, *LoginVerifyRequest) (*LoginVerifyResponse, error)
	mustEmbedUnimplementedAuthAPIServiceServer()
}

// UnimplementedAuthAPIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthAPIServiceServer struct{}

func (UnimplementedAuthAPIServiceServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedAuthAPIServiceServer) Auth(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Auth not implemented")
}
func (UnimplementedAuthAPIServiceServer) Signup(context.Context, *SignupRequest) (*SignupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Signup not implemented")
}
func (UnimplementedAuthAPIServiceServer) OTP(context.Context, *OTPRequest) (*OTPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method OTP not implemented")
}
func (UnimplementedAuthAPIServiceServer) SignUPVerify(context.Context, *SignUPVerifyRequest) (*SignUPVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignUPVerify not implemented")
}
func (UnimplementedAuthAPIServiceServer) LoginVerify(context.Context, *LoginVerifyRequest) (*LoginVerifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginVerify not implemented")
}
func (UnimplementedAuthAPIServiceServer) mustEmbedUnimplementedAuthAPIServiceServer() {}
func (UnimplementedAuthAPIServiceServer) testEmbeddedByValue()                        {}

// UnsafeAuthAPIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthAPIServiceServer will
// result in compilation errors.
type UnsafeAuthAPIServiceServer interface {
	mustEmbedUnimplementedAuthAPIServiceServer()
}

func RegisterAuthAPIServiceServer(s grpc.ServiceRegistrar, srv AuthAPIServiceServer) {
	// If the following call panics, it indicates UnimplementedAuthAPIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthAPIService_ServiceDesc, srv)
}

func _AuthAPIService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAPIService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_Auth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAPIService_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_Signup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAPIService_OTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).OTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_OTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).OTP(ctx, req.(*OTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAPIService_SignUPVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUPVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).SignUPVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_SignUPVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).SignUPVerify(ctx, req.(*SignUPVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthAPIService_LoginVerify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginVerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthAPIServiceServer).LoginVerify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthAPIService_LoginVerify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthAPIServiceServer).LoginVerify(ctx, req.(*LoginVerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthAPIService_ServiceDesc is the grpc.ServiceDesc for AuthAPIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthAPIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.v2.AuthAPIService",
	HandlerType: (*AuthAPIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _AuthAPIService_Login_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _AuthAPIService_Auth_Handler,
		},
		{
			MethodName: "Signup",
			Handler:    _AuthAPIService_Signup_Handler,
		},
		{
			MethodName: "OTP",
			Handler:    _AuthAPIService_OTP_Handler,
		},
		{
			MethodName: "SignUPVerify",
			Handler:    _AuthAPIService_SignUPVerify_Handler,
		},
		{
			MethodName: "LoginVerify",
			Handler:    _AuthAPIService_LoginVerify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v2/auth_api.proto",
}
