// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/v1/auth_api.proto

package auth_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OTPStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetStatus() *OTPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{2}
}

func (x *AuthRequest) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Userdata      *UserData              `protobuf:"bytes,1,opt,name=userdata,proto3" json:"userdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetUserdata() *UserData {
	if x != nil {
		return x.Userdata
	}
	return nil
}

type SignupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *Email                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupRequest) Reset() {
	*x = SignupRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupRequest) ProtoMessage() {}

func (x *SignupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupRequest.ProtoReflect.Descriptor instead.
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{4}
}

func (x *SignupRequest) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type OTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         *Token                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Userdata      *UserData              `protobuf:"bytes,2,opt,name=userdata,proto3" json:"userdata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPResponse) Reset() {
	*x = OTPResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPResponse) ProtoMessage() {}

func (x *OTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPResponse.ProtoReflect.Descriptor instead.
func (*OTPResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{5}
}

func (x *OTPResponse) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *OTPResponse) GetUserdata() *UserData {
	if x != nil {
		return x.Userdata
	}
	return nil
}

type OTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OTPRequest) Reset() {
	*x = OTPRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OTPRequest) ProtoMessage() {}

func (x *OTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OTPRequest.ProtoReflect.Descriptor instead.
func (*OTPRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{6}
}

func (x *OTPRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

type SignupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *OTPStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignupResponse) Reset() {
	*x = SignupResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignupResponse) ProtoMessage() {}

func (x *SignupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignupResponse.ProtoReflect.Descriptor instead.
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{7}
}

func (x *SignupResponse) GetStatus() *OTPStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type Email struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Email) Reset() {
	*x = Email{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Email) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Email) ProtoMessage() {}

func (x *Email) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Email.ProtoReflect.Descriptor instead.
func (*Email) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{8}
}

func (x *Email) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignUPVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Otp           string                 `protobuf:"bytes,1,opt,name=otp,proto3" json:"otp,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUPVerifyRequest) Reset() {
	*x = SignUPVerifyRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUPVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUPVerifyRequest) ProtoMessage() {}

func (x *SignUPVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUPVerifyRequest.ProtoReflect.Descriptor instead.
func (*SignUPVerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{9}
}

func (x *SignUPVerifyRequest) GetOtp() string {
	if x != nil {
		return x.Otp
	}
	return ""
}

func (x *SignUPVerifyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SignUPVerifyRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignUPVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response      *OTPResponse           `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUPVerifyResponse) Reset() {
	*x = SignUPVerifyResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUPVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUPVerifyResponse) ProtoMessage() {}

func (x *SignUPVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUPVerifyResponse.ProtoReflect.Descriptor instead.
func (*SignUPVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{10}
}

func (x *SignUPVerifyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *SignUPVerifyResponse) GetResponse() *OTPResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type LoginVerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Request       *OTPRequest            `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Email         *Email                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyRequest) Reset() {
	*x = LoginVerifyRequest{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyRequest) ProtoMessage() {}

func (x *LoginVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyRequest.ProtoReflect.Descriptor instead.
func (*LoginVerifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{11}
}

func (x *LoginVerifyRequest) GetRequest() *OTPRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *LoginVerifyRequest) GetEmail() *Email {
	if x != nil {
		return x.Email
	}
	return nil
}

type LoginVerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Response      *OTPResponse           `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginVerifyResponse) Reset() {
	*x = LoginVerifyResponse{}
	mi := &file_proto_v1_auth_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginVerifyResponse) ProtoMessage() {}

func (x *LoginVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_v1_auth_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginVerifyResponse.ProtoReflect.Descriptor instead.
func (*LoginVerifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_v1_auth_api_proto_rawDescGZIP(), []int{12}
}

func (x *LoginVerifyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *LoginVerifyResponse) GetResponse() *OTPResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_proto_v1_auth_api_proto protoreflect.FileDescriptor

const file_proto_v1_auth_api_proto_rawDesc = "" +
	"\n" +
	"\x17proto/v1/auth_api.proto\x12\bproto.v1\x1a\x15proto/v1/schema.proto\"5\n" +
	"\fLoginRequest\x12%\n" +
	"\x05email\x18\x01 \x01(\v2\x0f.proto.v1.EmailR\x05email\"<\n" +
	"\rLoginResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.proto.v1.OTPStatusR\x06status\"4\n" +
	"\vAuthRequest\x12%\n" +
	"\x05token\x18\x01 \x01(\v2\x0f.proto.v1.TokenR\x05token\">\n" +
	"\fAuthResponse\x12.\n" +
	"\buserdata\x18\x01 \x01(\v2\x12.proto.v1.UserDataR\buserdata\"6\n" +
	"\rSignupRequest\x12%\n" +
	"\x05email\x18\x01 \x01(\v2\x0f.proto.v1.EmailR\x05email\"d\n" +
	"\vOTPResponse\x12%\n" +
	"\x05token\x18\x01 \x01(\v2\x0f.proto.v1.TokenR\x05token\x12.\n" +
	"\buserdata\x18\x02 \x01(\v2\x12.proto.v1.UserDataR\buserdata\"\x1e\n" +
	"\n" +
	"OTPRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\"=\n" +
	"\x0eSignupResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\v2\x13.proto.v1.OTPStatusR\x06status\"\x1d\n" +
	"\x05Email\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"Y\n" +
	"\x13SignUPVerifyRequest\x12\x10\n" +
	"\x03otp\x18\x01 \x01(\tR\x03otp\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"a\n" +
	"\x14SignUPVerifyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x121\n" +
	"\bresponse\x18\x02 \x01(\v2\x15.proto.v1.OTPResponseR\bresponse\"k\n" +
	"\x12LoginVerifyRequest\x12.\n" +
	"\arequest\x18\x01 \x01(\v2\x14.proto.v1.OTPRequestR\arequest\x12%\n" +
	"\x05email\x18\x02 \x01(\v2\x0f.proto.v1.EmailR\x05email\"`\n" +
	"\x13LoginVerifyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x121\n" +
	"\bresponse\x18\x02 \x01(\v2\x15.proto.v1.OTPResponseR\bresponse2\x99\x03\n" +
	"\x0eAuthAPIService\x12:\n" +
	"\x05Login\x12\x16.proto.v1.LoginRequest\x1a\x17.proto.v1.LoginResponse\"\x00\x127\n" +
	"\x04Auth\x12\x15.proto.v1.AuthRequest\x1a\x16.proto.v1.AuthResponse\"\x00\x12=\n" +
	"\x06Signup\x12\x17.proto.v1.SignupRequest\x1a\x18.proto.v1.SignupResponse\"\x00\x124\n" +
	"\x03OTP\x12\x14.proto.v1.OTPRequest\x1a\x15.proto.v1.OTPResponse\"\x00\x12O\n" +
	"\fSignUPVerify\x12\x1d.proto.v1.SignUPVerifyRequest\x1a\x1e.proto.v1.SignUPVerifyResponse\"\x00\x12L\n" +
	"\vLoginVerify\x12\x1c.proto.v1.LoginVerifyRequest\x1a\x1d.proto.v1.LoginVerifyResponse\"\x00BOZMgithub.com/LLM-Finetuning-platform/go-auth-api/internal/handlers/grpc;auth_pbb\x06proto3"

var (
	file_proto_v1_auth_api_proto_rawDescOnce sync.Once
	file_proto_v1_auth_api_proto_rawDescData []byte
)

func file_proto_v1_auth_api_proto_rawDescGZIP() []byte {
	file_proto_v1_auth_api_proto_rawDescOnce.Do(func() {
		file_proto_v1_auth_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_v1_auth_api_proto_rawDesc), len(file_proto_v1_auth_api_proto_rawDesc)))
	})
	return file_proto_v1_auth_api_proto_rawDescData
}

var file_proto_v1_auth_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_v1_auth_api_proto_goTypes = []any{
	(*LoginRequest)(nil),         // 0: proto.v1.LoginRequest
	(*LoginResponse)(nil),        // 1: proto.v1.LoginResponse
	(*AuthRequest)(nil),          // 2: proto.v1.AuthRequest
	(*AuthResponse)(nil),         // 3: proto.v1.AuthResponse
	(*SignupRequest)(nil),        // 4: proto.v1.SignupRequest
	(*OTPResponse)(nil),          // 5: proto.v1.OTPResponse
	(*OTPRequest)(nil),           // 6: proto.v1.OTPRequest
	(*SignupResponse)(nil),       // 7: proto.v1.SignupResponse
	(*Email)(nil),                // 8: proto.v1.Email
	(*SignUPVerifyRequest)(nil),  // 9: proto.v1.SignUPVerifyRequest
	(*SignUPVerifyResponse)(nil), // 10: proto.v1.SignUPVerifyResponse
	(*LoginVerifyRequest)(nil),   // 11: proto.v1.LoginVerifyRequest
	(*LoginVerifyResponse)(nil),  // 12: proto.v1.LoginVerifyResponse
	(*OTPStatus)(nil),            // 13: proto.v1.OTPStatus
	(*Token)(nil),                // 14: proto.v1.Token
	(*UserData)(nil),             // 15: proto.v1.UserData
}
var file_proto_v1_auth_api_proto_depIdxs = []int32{
	8,  // 0: proto.v1.LoginRequest.email:type_name -> proto.v1.Email
	13, // 1: proto.v1.LoginResponse.status:type_name -> proto.v1.OTPStatus
	14, // 2: proto.v1.AuthRequest.token:type_name -> proto.v1.Token
	15, // 3: proto.v1.AuthResponse.userdata:type_name -> proto.v1.UserData
	8,  // 4: proto.v1.SignupRequest.email:type_name -> proto.v1.Email
	14, // 5: proto.v1.OTPResponse.token:type_name -> proto.v1.Token
	15, // 6: proto.v1.OTPResponse.userdata:type_name -> proto.v1.UserData
	13, // 7: proto.v1.SignupResponse.status:type_name -> proto.v1.OTPStatus
	5,  // 8: proto.v1.SignUPVerifyResponse.response:type_name -> proto.v1.OTPResponse
	6,  // 9: proto.v1.LoginVerifyRequest.request:type_name -> proto.v1.OTPRequest
	8,  // 10: proto.v1.LoginVerifyRequest.email:type_name -> proto.v1.Email
	5,  // 11: proto.v1.LoginVerifyResponse.response:type_name -> proto.v1.OTPResponse
	0,  // 12: proto.v1.AuthAPIService.Login:input_type -> proto.v1.LoginRequest
	2,  // 13: proto.v1.AuthAPIService.Auth:input_type -> proto.v1.AuthRequest
	4,  // 14: proto.v1.AuthAPIService.Signup:input_type -> proto.v1.SignupRequest
	6,  // 15: proto.v1.AuthAPIService.OTP:input_type -> proto.v1.OTPRequest
	9,  // 16: proto.v1.AuthAPIService.SignUPVerify:input_type -> proto.v1.SignUPVerifyRequest
	11, // 17: proto.v1.AuthAPIService.LoginVerify:input_type -> proto.v1.LoginVerifyRequest
	1,  // 18: proto.v1.AuthAPIService.Login:output_type -> proto.v1.LoginResponse
	3,  // 19: proto.v1.AuthAPIService.Auth:output_type -> proto.v1.AuthResponse
	7,  // 20: proto.v1.AuthAPIService.Signup:output_type -> proto.v1.SignupResponse
	5,  // 21: proto.v1.AuthAPIService.OTP:output_type -> proto.v1.OTPResponse
	10, // 22: proto.v1.AuthAPIService.SignUPVerify:output_type -> proto.v1.SignUPVerifyResponse
	12, // 23: proto.v1.AuthAPIService.LoginVerify:output_type -> proto.v1.LoginVerifyResponse
	18, // [18:24] is the sub-list for method output_type
	12, // [12:18] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_v1_auth_api_proto_init() }
func file_proto_v1_auth_api_proto_init() {
	if File_proto_v1_auth_api_proto != nil {
		return
	}
	file_proto_v1_schema_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_v1_auth_api_proto_rawDesc), len(file_proto_v1_auth_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_v1_auth_api_proto_goTypes,
		DependencyIndexes: file_proto_v1_auth_api_proto_depIdxs,
		MessageInfos:      file_proto_v1_auth_api_proto_msgTypes,
	}.Build()
	File_proto_v1_auth_api_proto = out.File
	file_proto_v1_auth_api_proto_goTypes = nil
	file_proto_v1_auth_api_proto_depIdxs = nil
}
