name: Auth Dev CD

on:  
    push: 
      branches: 
         - develop
         - main
              
jobs:
    buf-auth-cd:
        uses: LLM-Finetuning-platform/shared-workflows/.github/workflows/buf-cd.yaml@main
        secrets: inherit