name: Auth Dev CI

on:  
    pull_request: 
      branches: 
         - develop
         - main
jobs:
    buf-auth-ci:
        uses: LLM-Finetuning-platform/shared-workflows/.github/workflows/buf-ci.yaml@main
    go-auth-ci:
        uses: LLM-Finetuning-platform/shared-workflows/.github/workflows/go-ci.yaml@main
  
        
